name: Trigger Bahmni Package
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

env:
  ORG_NAME: Bahmni
  EVENT_TYPE: atomfeed-console-trigger
jobs:
  trigger-dependent-repos:
    name: Trigger Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Create repository_dispatch
        env:
          REPOSITORY_NAME: bahmni-package
        run: |
          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
          if [ $trigger_result == 204 ];then
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
          else
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
            cat trigger_response.txt
            exit 1
          fi