name: Build & Publish atomfeed-console
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  build-atomfeed-console:
    name: Build atomfeed-console
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "8"
      # - name: Run Unit Tests
      #   run: mvn --no-transfer-progress clean test
      - name: Install bower
        run: npm install -g bower 
      - name: Package
        run: mvn --no-transfer-progress clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: atomfeed-console-SNAPSHOT.jar
          path: target/*.jar

  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    needs: 
      - Trivy
      - build-atomfeed-console
    steps:
      - uses: actions/checkout@v2
      - name: Verify app version
        run: |
          APP_VERSION=$(cat package/docker/.appversion)
          if [ $(git tag -l "$APP_VERSION") ]; then 
            echo "App version $APP_VERSION already released. Please update app version in package/docker/.appversion to represent next major/minor/patch increment"
            exit 1
          else
            echo "setting artifact version to $(echo $APP_VERSION-${{github.run_number}})"
            echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
          fi
      - name: Download atomfeed-console jar
        uses: actions/download-artifact@v2
        with:
          name: atomfeed-console-SNAPSHOT.jar
          path: package/docker/resources/
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: true
          push: true
          tags: bahmni/atomfeed-console:${{env.ARTIFACT_VERSION}},bahmni/atomfeed-console:latest
  